import { Bree_Serif } from "next/font/google";
import "./globals.css";
import Provider from "./Provider";
import { ClerkProvider } from "@clerk/nextjs";


const bree_serif=Bree_Serif({
  subsets:['latin'],
  weight:'400'
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body
        className={bree_serif.className}
      >
        
        <Provider>

        {children}
        </Provider>
      </body>
    </html>
    </ClerkProvider>
  );
}
